# Generated by Django 5.2.16 on 2026-09-15 02:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_phone_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('window_start', models.BigIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'window_start'), name='unique_identity_rate_window')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=64)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('ip_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.CharField(default='phone_verification', max_length=32)),
                ('session_binding', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('superseded', 'Superseded'), ('locked', 'Locked')], default='queued', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('provider_pin_id', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('delivery_status', models.CharField(blank=True, max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verification_lease', models.UUIDField(blank=True, null=True)),
                ('verifying_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_deadline', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resend_available_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_challenges', to='transactions.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='phone_user_created_idx'), models.Index(fields=['status', 'created_at'], name='phone_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_phone_request_key'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'purpose'), name='one_active_phone_challenge')],
            },
        ),
    ]
