# Generated by Django 5.2.14 on 2026-09-18 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('transactions', '0006_phone_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('nin', 'NIN Verification'), ('bvn', 'BVN Verification'), ('cac', 'CAC Verification')], max_length=16)),
                ('provider', models.CharField(default='dojah', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('requires_review', 'Requires Review')], default='pending', max_length=24)),
                ('id_hash', models.CharField(db_index=True, max_length=64)),
                ('masked_id', models.CharField(max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=256)),
                ('match_score', models.FloatField(default=0.0)),
                ('failure_reason', models.CharField(blank=True, max_length=128)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to='transactions.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to='transactions.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='kyc_user_created_idx'), models.Index(fields=['status', 'created_at'], name='kyc_status_created_idx')],
            },
        ),
    ]
