server {
    listen 80;
    server_name 13.49.183.176;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/vurex-server/staticfiles/;
    }

    location /media/ {
        alias /var/www/vurex-server/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
