# Generated by Django 5.2.16 on 2026-07-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_otpcode_transaction_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
