# Generated by Django 5.2.14 on 2026-07-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
