# Generated by Django 5.2.14 on 2026-07-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_dispute_description_transaction_disputed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='defense_evidence_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='defense_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='defense_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
