# Generated by Django 5.2.16 on 2026-09-15 02:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_phone_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySmsBudget',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=32)),
                ('object_id', models.UUIDField()),
                ('deduplication_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='dispatch_due_idx'), models.Index(fields=['status', 'locked_at'], name='dispatch_lease_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=20)),
                ('template', models.CharField(max_length=64)),
                ('deduplication_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='sending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('provider_event_id', models.CharField(blank=True, max_length=160)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('delivery_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'received_at'], name='receipt_status_received_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='notif_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'attempt'), name='notif_unique_attempt'),
        ),
    ]
